name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'maven'
        java-version: '3.8.1'

    - name: SonarQube Analysis
      run: |
        mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN

    - name: Build with Maven
      run: mvn clean install
