name: Build and Analyze

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.dev.SONAR_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK and Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        maven-version: '3.8.1' # Specify the desired Maven version

    - name: SonarQube Analysis
      run: |
        mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN

    - name: Build with Maven
      run: mvn clean install